#!/usr/bin/env bash
#copies the file specified by the user to a server specified by user
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -F $4 $1 $3@$2:~/
fi
