#!/usr/bin/env bash
# this script installs an nginx web server
sudo apt-update
sudo apt-install nginx
sudo systemctl status nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'OpenSSH'
sudo ufw allow ssh
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
