#!/usr/bin/env bash
# this script installs an nginx web server
sudo apt-update -y
sudo apt-install nginx -y
sudo apt install ufw -y
sudo ufw allow 'Nginx HTTP'
sudo ufw allow ssh
sudo ufw allow 'OpenSSH'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
