#!/usr/bin/env bash
# this script installs an nginx web server
sudo apt-update -y
sudo apt-install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'OpenSSH'
sudo ufw allow ssh
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
