#!/usr/bin/env bash
# this script installs an nginx web server
sudo apt update -y
sudo apt install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
new_str="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
sed -i "s/server_name _;/$new_str/" /etc/nginx/sites-enabled/default
service nginx start
