#!/usr/bin/env bash
# this script installs an nginx web server
sudo apt update -y
sudo apt install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
new_str="server_name _\n\trewrite ^\/redirect_me$\ngoogle.com permanent;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\troot \/usr\/share\/nginx\/html;\n\tinternal;}"
sed -i "s/server_name _;/$new_str/" /etc/nginx/sites-enabled/default
service nginx start
