#!/usr/bin/env bash
# this script installs a load balancer
sudo apt-get update -y
sudo apt-get install haproxy -y
echo -e "\nfrontend Server\n\tbind *:80\n\tmode http\n\tdefault_backend nodes\n\nbackend nodes\n\tbalance roundrobin\n\tserver 1087-web-01 35.231.149.204:80 check\n\tserver 1087-web-02 34.228.66.193:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
