#!/usr/bin/env bash
# this script makes a compressed archive out of a database
if [ $# -gt 0 ]
then
    pass="$1"
else
    pass=""
fi

mysqldump --all-databases --user=root --password=$pass > backup.sql
now=(date +'%d-%m-%Y')
tar -czf "$now".tar.gz backup.sql
