#!/usr/bin/env bash
#this script shows "to infinity andbeyond indefinitely"
trap wont SIGTERM
wont()
{
    echo "I won't die"
}
bool=1
while [ $bool = 1 ]
do
    echo "To infinity and beyond"
    sleep 2
done
