#!/usr/bin/env bash
# This script prints holberton school 10 times using while
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 9 ]; then
	echo "Holberton School"
	echo "Hi";
    else
	echo "Holberton School"
    fi
    i=$(( i+ 1 ))
done
