#!/usr/bin/env bash
# This script loops from 1 to 10 bad luck if 4th iter good luck in 8th iter
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]; then
	echo "bad luck"
    elif [ $i -eq 8 ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    i=$(( i+ 1 ))
done
