#!/usr/bin/env bash
# This script displays a list of all my files
file="./holbertonschool"
if [ ! "$file" ]; then
    echo "holbertonschool file does not exist"
else
    echo "holbertonschool file exists"
    if [ -s "$file" ]; then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi

    if [ -f "$file" ]; then
	echo  "holbertonschool is a regular file"
    fi
fi
